binary_sensor:
  - platform: mqtt
    name: 'Hallway Motion'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_hallway_motion
    payload_off: clear_hallway_motion
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: motion
    qos: 1
  - platform: mqtt
    name: 'Front Door'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_front_door_activate
    payload_off: !secret rf_front_door_clear
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: door
    qos: 1
  - platform: mqtt
    name: 'Bedroom Left Door'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_bedroom_left_door_activate
    payload_off: !secret rf_bedroom_left_door_clear
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: door
    qos: 1
  - platform: mqtt
    name: 'Bedroom Right Door'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_bedroom_right_door_activate
    payload_off: !secret rf_bedroom_right_door_clear
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: door
    qos: 1
  - platform: mqtt
    name: 'Spare Room Window'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_spare_room_window_activate
    payload_off: !secret rf_spare_room_window_clear
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: window
    qos: 1
  - platform: mqtt
    name: 'Spare Room Window Break'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_spare_room_window_break
    payload_off: clear_spare_room_window_break
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: vibration
    qos: 1

group:
  physical_sensors:
    name: Physical Sensors
    entities:
      - binary_sensor.hallway_motion
      - binary_sensor.front_door
      - binary_sensor.spare_room_window_break
      - binary_sensor.bedroom_left_door
      - binary_sensor.bedroom_right_door
      - binary_sensor.spare_room_window_break

automation:
  - alias: Clear Hallway Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: 'on'
        for:
          seconds: 5
    action:
      - service: mqtt.publish
        data:
          topic: tele/rf/RESULT
          payload: clear_hallway_motion
  - alias: Clear Spare Room Window Break
    trigger:
      - platform: state
        entity_id: binary_sensor.spare_room_window_break
        to: 'on'
        for:
          seconds: 5
    action:
      - service: mqtt.publish
        data:
          topic: tele/rf/RESULT
          payload: clear_spare_room_window_break


