binary_sensor:
  - platform: mqtt
    name: 'Hallway Motion'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_hallway_motion
    payload_off: clear_hallway_motion
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
  - platform: mqtt
    name: 'Front Door'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_front_door
    payload_off: clear_front_door
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
  - platform: mqtt
    name: 'Spare Room Window Break'
    state_topic: 'tele/rf/RESULT'
    value_template: '{{ value_json.RfReceived.Data }}'
    payload_on: !secret rf_spare_room_window_break
    payload_off: clear_spare_room_window_break
    availability_topic: "tele/rf/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1

group:
  physical_sensors:
    name: Physical Sensors
    entities:
      - binary_sensor.hallway_motion
      - binary_sensor.front_door
      - binary_sensor.spare_room_window_break

automation:
  - alias: Clear Hallway Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: 'on'
        for:
          seconds: 5
    action:
      - service: mqtt.publish
        data:
          topic: tele/rf/RESULT
          payload: clear_hallway_motion
  - alias: Clear Front Door
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: 'on'
        for:
          seconds: 5
    action:
      - service: mqtt.publish
        data:
          topic: tele/rf/RESULT
          payload: clear_front_door
  - alias: Clear Spare Room Window Break
    trigger:
      - platform: state
        entity_id: binary_sensor.spare_room_window_break
        to: 'on'
        for:
          seconds: 5
    action:
      - service: mqtt.publish
        data:
          topic: tele/rf/RESULT
          payload: clear_spare_room_window_break


