alarm_control_panel:
  - platform: manual
    name: Alarm
    code_template: ''
    delay_time: 30
    arming_time: 30
    trigger_time: 300

automation:
  - alias: 'Trigger alarm while armed away'
    trigger:
      - platform: state
        entity_id: group.away_alarm_sensors
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
  - alias: 'Trigger alarm while armed home'
    trigger:
      - platform: state
        entity_id: group.home_alarm_sensors
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_home
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

notify:
  - platform: group
    name: alarm
    services:
      - service: twilio_sms
        data:
          target:
            - !secret antony_phone
      - service: twilio_call
        data:
          target:
            - !secret antony_phone
      - service: mobile_app_sm_g975f

alert:
  alarm_triggered:
    name: Alarm has been triggered
    message: "Alarm triggered. {%- for item in expand('group.away_alarm_sensors') %}
{{ item.name }}: {{ item.state }} ({{ relative_time(item.last_changed) }} ago)
{%- endfor %}"
    done_message: Alarm has been reset
    entity_id: alarm_control_panel.alarm
    state: 'triggered'
    repeat: 1
    notifiers:
      - alarm

group:
  home_alarm_sensors:
    name: Home Alarm Sensors
    entities:
      - binary_sensor.front_door
      - binary_sensor.spare_room_window_break
  away_alarm_sensors:
    name: Away Alarm Sensors
    entities:
      - group.home_alarm_sensors
      - binary_sensor.hallway_motion
