device_tracker:
  - platform: mqtt_json
    devices:
      kona: kona/location

sensor:
  - platform: mqtt
    name: "Kona Charge Remaining"
    state_topic: "kona/status"
    value_template: '{{ value_json["remainingMin"] }}'
    device_class: timestamp
    force_update: true
  - platform: template
    sensors:
      kona_charge_done:
        friendly_name: 'Kona Charge Done'
        device_class: timestamp
        value_template: "{{ ((now() | as_timestamp) + (states('sensor.kona_charge_remaining') | int * 60 )) | timestamp_local  }}"
  - platform: mqtt
    name: "Kona Battery"
    state_topic: "kona/status"
    value_template: '{{ value_json["battery"] }}'
    unit_of_measurement: "%"
    force_update: true
  - platform: mqtt
    name: "Kona 12v Battery"
    state_topic: "kona/status"
    value_template: '{{ value_json["battery-12v"] }}'
    unit_of_measurement: "%"
  - platform: mqtt
    name: "Kona Odometer"
    state_topic: "kona/status"
    value_template: '{{ value_json["odometer"] }}'
    unit_of_measurement: "miles"
  - platform: mqtt
    name: "Kona Range"
    state_topic: "kona/status"
    value_template: '{{ value_json["range"] }}'
    unit_of_measurement: "miles"
  - platform: template
    sensors:
      kona_updated:
        friendly_name: 'Kona Updated'
        device_class: timestamp
        value_template: "{{ states.sensor.kona_battery.last_updated }}"

binary_sensor:
  - platform: mqtt
    name: "Kona Engine"
    payload_on: true
    payload_off: false
    state_topic: "kona/status"
    value_template: '{{ value_json["engine"] }}'
  - platform: mqtt
    name: "Kona Locked"
    payload_on: false
    payload_off: true
    state_topic: "kona/status"
    value_template: '{{ value_json["locked"] }}'
  - platform: mqtt
    name: "Kona Battery Charging"
    payload_on: true
    payload_off: false
    state_topic: "kona/status"
    value_template: '{{ value_json["charging"] }}'

homeassistant:
  customize:
    binary_sensor.kona_locked:
      device_class: lock
    binary_sensor.kona_battery_charging:
      device_class: battery_charging
      icon: mdi:ev-station
    sensor.kona_12v_battery:
      device_class: battery
    sensor.kona_odometer:
      icon: mdi:speedometer-medium
    sensor.kona_range:
      icon: mdi:speedometer-medium

