circadian_lighting:

switch:
  - name: Front Room Circadian
    platform: circadian_lighting
    lights_brightness:
      - light.kitchen
      - light.lounge
  - name: Bedroom Circadian
    platform: circadian_lighting
    lights_brightness:
      - light.bedroom

homeassistant:
  customize_glob:
    "switch.circadian_lighting_*":
      friendly_name: 'Auto Brightness'
