
automation:
  - id: 36d89286-74af-4f5a-9687-ba9046ef70c0
    alias: Bottom Left Double Tap
    trigger:
    - event_data:
        node_id: 4
        scene_value_id: 14
        scene_value_label: Scene
      event_type: ozw.scene_activated
      platform: event
    action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.front_room

group:
  front_room:
    name: Front Room
    entities:
      - light.lounge
      - light.lounge_lamp
      - light.kitchen
