
automation:
  - id: 36d89286-74af-4f5a-9687-ba9046ef70c0
    alias: Bottom Left Double Tap
    trigger:
    - event_data:
        entity_id: zwave.kitchen_dimmer
        scene_id: 14
      event_type: zwave.scene_activated
      platform: event
    action:
    - device_id: 0b840fc0d5924903be494f3fda187d21
      domain: light
      entity_id: light.kitchen
      type: turn_off
    - device_id: ea6f01621a9a4daf91211d6a9dadcadf
      domain: light
      entity_id: light.lounge
      type: turn_off
    - data:
        payload: 'OFF'
        topic: cmnd/lamp/POWER
      service: mqtt.publish
