
automation:
  - id: 36d89286-74af-4f5a-9687-ba9046ef70c0
    alias: Bottom Left Double Tap
    trigger:
    - event_data:
        entity_id: zwave.kitchen_dimmer
        scene_id: 14
      event_type: zwave.scene_activated
      platform: event
    action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.front_room

group:
  front_room:
    name: Front Room
    entities:
      - light.lounge
      - light.lounge_lamp
      - light.kitchen
