logger:
  logs:
    homeassistant.components.homekit: debug

sensor:
  - platform: template
    sensors:
      temperature_lounge_kitchen:
        friendly_name: "Lounge & Kitchen Temperature"
        value_template: "{{ state_attr('climate.lounge_kitchen', 'current_temperature') }}"
        unit_of_measurement: "째C"
        device_class: "temperature"
      temperature_bathroom_hallway:
        friendly_name: "Hallway & Bathroom Temperature"
        value_template: "{{ state_attr('climate.bathroom_hallway', 'current_temperature') }}"
        unit_of_measurement: "째C"
        device_class: "temperature"
      temperature_master_bedroom:
        friendly_name: "Bedroom Temperature"
        value_template: "{{ state_attr('climate.master_bedroom', 'current_temperature') }}"
        unit_of_measurement: "째C"
        device_class: "temperature"
      temperature_study:
        friendly_name: "Study Temperature"
        value_template: "{{ state_attr('climate.study', 'current_temperature') }}"
        unit_of_measurement: "째C"
        device_class: "temperature"

switch:
  - platform: template
    switches:
      heating_lounge_kitchen:
        friendly_name: "Heating Living Room"
        value_template: "{{ 'on' if states('switch.lounge_kitchen_standby') == 'off' else 'off' }}"
        icon_template: "{{ 'mdi:fire' if states('switch.heating_lounge_kitchen') == 'on' else 'mdi:snowflake' }}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.lounge_kitchen_standby
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.lounge_kitchen_standby
      heating_bathroom_hallway:
        friendly_name: "Heating Hallway & Bathroom"
        value_template: "{{ 'on' if states('switch.bathroom_hallway_standby') == 'off' else 'off' }}"
        icon_template: "{{ 'mdi:fire' if states('switch.heating_bathroom_hallway') == 'on' else 'mdi:snowflake' }}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.bathroom_hallway_standby
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.bathroom_hallway_standby
      heating_master_bedroom:
        friendly_name: "Heating Bedroom"
        value_template: "{{ 'on' if states('switch.master_bedroom_standby') == 'off' else 'off' }}"
        icon_template: "{{ 'mdi:fire' if states('switch.heating_master_bedroom') == 'on' else 'mdi:snowflake' }}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.master_bedroom_standby
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.master_bedroom_standby
      heating_study:
        friendly_name: "Study Room"
        value_template: "{{ 'on' if states('switch.study_standby') == 'off' else 'off' }}"
        icon_template: "{{ 'mdi:fire' if states('switch.heating_study') == 'on' else 'mdi:snowflake' }}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.study_standby
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.study_standby
homeassistant:
  customize_glob:
    "switch.*_standby":
      icon: 'mdi:snowflake'
