pi_hole:
  host: '10.25.0.50'
  ssl: false
  verify_ssl: false
  api_key: !secret pi_hole_api

script:
  pause_pi_hole:
    alias: Pause Pi-Hole 15m
    sequence:
    - service: pi_hole.disable
      data:
        duration: 00:15:00
      entity_id: switch.pi_hole
    mode: single
    icon: mdi:pause
