sensor:
  - platform: command_line
    command: !secret simplesocket_mid_command
    name: simplesocket_mid
    value_template: &simplesocket_value_template >-
      {% set map = {
        "AVAILABLE": "Free",
        "CHARGING": "Charging",
        "FAULED": "Out of service",
        "FINISHING": "Charging (Finishing)",
        "MM_AVAILABLE": "Free",
        "MM_CONNECTED": "Charging (Smart)",
        "PREPARING": "Plugged In",
        "SUSPENDED_EV": "Squatting",
        "SUSPENDED_EVSE": "Squatting",
      } %}

      {{ map[value] | default(value) }}
    scan_interval: 300
  - platform: command_line
    command: !secret simplesocket_top_command
    name: simplesocket_top
    scan_interval: 300
    value_template: *simplesocket_value_template

homeassistant:
  customize:
    sensor.simplesocket_mid:
      friendly_name: 'Mid'
      icon: 'mdi:ev-station'
    sensor.simplesocket_top:
      friendly_name: 'Top'
      icon: 'mdi:ev-station'
