sensor:
  - platform: uk_transport
    app_id: !secret uk_transport_app_id
    app_key: !secret uk_transport_app_key
    queries:
      - mode: train
        origin: EPH
        destination: SRT
      - mode: train
        origin: EPH
        destination: HNH
