sensor:
  - platform: mqtt
    name: "Washing Machine Energy Today"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Washing Machine Power"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Washing Machine Voltage"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Washing Machine Current"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"
    
binary_sensor:
  - platform: template
    sensors:
      washing_machine_running:
        friendly_name: "Washing Machine Running"
        delay_off:
          minutes: 2
        value_template: >-
          {{ states('sensor.washing_machine_power')|float > 0 }}

group:
  washing_machine:
    entities:
      - sensor.washing_machine_energy_today
      - sensor.washing_machine_power
      - sensor.washing_machine_voltage
      - sensor.washing_machine_current
      - binary_sensor.washing_machine_running

input_boolean:
  washing_machine_needs_emptying:
    name: Washing machine needs emptying
    icon: mdi:basket-fill

automation:
  - id: washing_machine_alert_to_toggle
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_running
        to: 'off'
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.washing_machine_needs_emptying

alert:
  washing_machine_needs_emptying:
    name: Washing machine needs emptying
    done_message: Washing machine is empty
    entity_id: input_boolean.washing_machine_needs_emptying
    state: 'on'
    repeat:
      - 5
      - 10
      - 30
      - 60
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_g975f

homeassistant:
  customize:
    binary_sensor.washing_machine_running:
      device_class: moving
      icon: 'mdi:washing-machine'
