sensor:
  - platform: mqtt
    name: "Washing Machine Energy Today"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Washing Machine Power"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Washing Machine Voltage"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - platform: mqtt
    name: "Washing Machine Current"
    state_topic: "tele/washing/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"
  - platform: time_date
    display_options:
      - 'time'

switch:
  - platform: switchbot
    mac: 'C3:C2:40:62:C5:59'
    name: 'Washing Machine Start'
  - platform: mqtt
    name: "Washing Machine Power Supply"
    state_topic: "stat/washing/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/washing/POWER"
    availability_topic: "tele/tasmota/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    
binary_sensor:
  - platform: template
    sensors:
      washing_machine_running:
        friendly_name: "Washing Machine Running"
        delay_off:
          minutes: 2
        value_template: >-
          {{ states('sensor.washing_machine_power')|float > 5 }}
      washing_machine_power_supply:
        friendly_name: "Washing Machine Power Supply"
        value_template: >-
          {{ states('switch.washing_machine_power_supply') == 'on' }}

group:
  washing_machine:
    entities:
      - sensor.washing_machine_energy_today
      - sensor.washing_machine_power
      - sensor.washing_machine_voltage
      - sensor.washing_machine_current
      - binary_sensor.washing_machine_running

input_boolean:
  washing_machine_needs_emptying:
    name: Washing machine needs emptying
    icon: mdi:basket-fill
  auto_start_washing_machine:
    name: Auto Start Wash
    icon: mdi:clock
  auto_start_washing_machine_resume:
    name: Resume Wash
    icon: mdi:pause

input_datetime:
  washing_machine_start:
    name: Start Washing Machine At
    has_time: true
    has_date: false

automation:
  - id: washing_machine_alert_to_toggle
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_running
        to: 'off'
    action:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.washing_machine_needs_emptying
  - id: washing_machine_auto_start
    alias: 'Auto start washing machine'
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.washing_machine_start', 'timestamp') | int | timestamp_custom('%H:%M', false)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.auto_start_washing_machine
        state: 'on'
    action:
      - service: script.washing_machine_power_on
      - service: script.start_wash
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.auto_start_washing_machine

script:
  washing_machine_power_on:
    sequence:
      - condition: state
        entity_id: binary_sensor.washing_machine_running
        state: 'off'
      - condition: state
        entity_id: input_boolean.auto_start_washing_machine_resume
        state: 'off'
      - service: switch.turn_off
        data:
          entity_id: switch.washing_machine_power_supply
      - delay: '00:00:01'
      - service: switch.turn_on
        data:
          entity_id: switch.washing_machine_power_supply
  start_wash:
    sequence:
      - delay: '00:00:03'
      - service: switch.toggle
        data:
          entity_id: switch.washing_machine_start

alert:
  washing_machine_needs_emptying:
    name: Washing machine needs emptying
    done_message: Washing machine has been emptied
    entity_id: input_boolean.washing_machine_needs_emptying
    state: 'on'
    repeat:
      - 5
      - 10
      - 30
      - 60
    can_acknowledge: true
    skip_first: false
    notifiers:
      - mobile_app_sm_g975f

homeassistant:
  customize:
    binary_sensor.washing_machine_running:
      device_class: moving
      icon: 'mdi:washing-machine'
