---
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2021.1.5
    volumes:
      - ./config:/config
      - /dev/bus/usb:/dev/bus/usb
    restart: always
    environment:
      USER_ID: 1001
      GROUP_ID: 1001
    network_mode: host
  mosquitto:
    image: "eclipse-mosquitto:1.6.9"
    restart: always
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    env_file: uidgid.env
    environment:
      USER_ID: 1001
      GROUP_ID: 1001
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - connected

networks:
  connected:
    external:
      name: connected
