
sensor:
  - platform: template
    sensors:
      wall_plug_1_cost:
        friendly_name: "Wall Plug 1 Cost"
        value_template: >-
          {{ '{:,.2f}'.format(states('sensor.wall_plug_1_energy')|float * states('input_number.price_per_kwh') | float) }}
        unit_of_measurement: '£'
        icon_template: 'mdi:currency-gbp'

binary_sensor:
  - platform: template
    sensors:
      wall_plug_1:
        friendly_name: "Wall Plug 1"
        value_template: "{{ states('switch.wall_plug_1') == 'on'  }}"
        device_class: 'power'

homeassistant:
  customize:
    light.lounge:
      friendly_name: 'Lounge'
      icon: 'mdi:wall-sconce-flat'
    light.kitchen:
      friendly_name: 'Kitchen'
      icon: 'mdi:wall-sconce-flat'
    light.bathroom:
      friendly_name: 'Bathroom'
      icon: 'mdi:wall-sconce-flat'
    light.bedroom:
      friendly_name: 'Bedroom'
      icon: 'mdi:globe-light'
    switch.bathroom_fan:
      friendly_name: 'Bathroom Fan'
      icon: 'mdi:fan'

