homeassistant:
  name: Home
  latitude: 51.496530
  longitude: -0.097310
  elevation: 6
  unit_system: metric
  time_zone: Europe/London
  external_url: !secret hass_external_url
  internal_url: !secret hass_external_url
  whitelist_external_dirs:
    - /tmp
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: fritz
    track_new_devices: True
    host: 192.168.0.1
