views:
  - badges: []
    cards:
      - entities:
          - entity: light.kitchen
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.lounge
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.lounge_lamp
          - type: divider
          - entity: switch.circadian_lighting_front_room_circadian
        show_header_toggle: false
        title: Lounge
        type: entities
      - entities:
          - entity: light.bedroom
            toggle: true
            type: 'custom:slider-entity-row'
          - type: divider
          - entity: switch.circadian_lighting_bedroom_circadian
        show_header_toggle: false
        title: Bedroom
        type: entities
      - entities:
          - entity: light.bathroom
          - entity: switch.bathroom_fan
        show_header_toggle: false
        title: Bathroom
        type: entities
      - entities:
          - entity: binary_sensor.washing_machine_running
          - type: divider
          - entity: input_boolean.auto_start_washing_machine
          - entity: input_boolean.auto_start_washing_machine_resume
          - entity: input_datetime.washing_machine_start
        show_header_toggle: false
        title: Washing Machine
        type: entities
      - type: media-control
        entity: media_player.samsung_tv_remote
      - type: media-control
        entity: media_player.living_room_speaker
      - type: media-control
        entity: media_player.home_group
    path: home
    title: Home
