views:
  - badges: []
    cards:
      - entity: weather.met_office_southwark
        type: weather-forecast
      - card:
          entity: input_boolean.washing_machine_needs_emptying
          type: button
        conditions:
          - entity: input_boolean.washing_machine_needs_emptying
            state: 'on'
        type: conditional
      - entities:
          - entity: light.kitchen
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.lounge
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.lounge_lamp
          - type: divider
          - entity: switch.circadian_lighting_front_room_circadian
        show_header_toggle: false
        title: Lounge
        type: entities
      - entities:
          - entity: light.bedroom
            toggle: true
            type: 'custom:slider-entity-row'
          - type: divider
          - entity: switch.circadian_lighting_bedroom_circadian
        show_header_toggle: false
        title: Bedroom
        type: entities
      - entities:
          - entity: light.bathroom
          - entity: switch.bathroom_fan
        show_header_toggle: false
        title: Bathroom
        type: entities
      - entities:
          - entity: binary_sensor.washing_machine_running
          - type: divider
          - entity: input_boolean.auto_start_washing_machine
          - entity: input_boolean.auto_start_washing_machine_resume
          - entity: input_datetime.washing_machine_start
        show_header_toggle: false
        title: Washing Machine
        type: entities
    icon: 'mdi:home'
    path: home
    title: ''
  - icon: 'mdi:music'
    badges: []
    cards:
      - entity: media_player.samsung_tv_remote
        type: media-control
      - entity: media_player.living_room_speaker
        type: media-control
      - entity: media_player.home_group
        type: media-control
  - badges: []
    cards:
      - content: >-

          {% set next = state_attr('sensor.next_train_to_hnh', 'next_trains')[0]
          %}


          **Destination:** {{ next.destination_name }}

          **Platform:** {{ next.platform }}

          **Time:** {% if next.scheduled == next.estimated -%}
            {{ next.estimated }}
          {% else -%}
            {{ next.scheduled }} (expected: {{ next.estimated }})
          {% endif -%}


          {% set following = state_attr('sensor.next_train_to_hnh',
          'next_trains')[1] %}

          **Next:** {% if following.scheduled == following.estimated -%}
            {{ following.estimated }}
          {% else -%}
            {{ following.scheduled }} (expected: {{ following.estimated }})
          {% endif -%}
        title: Next Train to Herne Hill
        type: markdown
      - content: >-

          {% set next = state_attr('sensor.next_train_to_srt', 'next_trains')[0]
          %}


          **Destination:** {{ next.destination_name }}

          **Platform:** {{ next.platform }}

          **Time:** {% if next.scheduled == next.estimated -%}
            {{ next.estimated }}
          {% else -%}
            {{ next.scheduled }} (expected: {{ next.estimated }})
          {% endif -%}


          {% set following = state_attr('sensor.next_train_to_srt',
          'next_trains')[1] %}

          **Next:** {% if following.scheduled == following.estimated -%}
            {{ following.estimated }}
          {% else -%}
            {{ following.scheduled }} (expected: {{ following.estimated }})
          {% endif -%}
        title: Next Train to Shortlands
        type: markdown
    icon: 'mdi:train'
    path: trains
    title: ''
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.hallway_motion
          - entity: binary_sensor.front_door
          - entity: binary_sensor.spare_room_window_break
          - entity: binary_sensor.bedroom_left_door
          - entity: binary_sensor.bedroom_right_door
          - entity: binary_sensor.spare_room_window
        title: Sensors
        type: entities
      - entity: alarm_control_panel.alarm
        states:
          - arm_home
          - arm_away
        type: alarm-panel
    icon: 'mdi:motion-sensor'
    path: physical
    title: ''
  - badges: []
    cards:
      - entities:
          - entity: device_tracker.kona
        geo_location_sources: []
        hours_to_show: 12
        type: map
      - entities:
          - entity: binary_sensor.kona_locked
            name: Locked
          - type: divider
          - entity: sensor.kona_battery
            name: Battery
          - entity: sensor.kona_12v_battery
            name: 12v Battery
          - entity: sensor.kona_range
            name: Range
          - entity: binary_sensor.kona_battery_charging
            name: Charging
          - type: divider
          - entity: sensor.kona_updated
            name: Last Updated
            icon: 'mdi:clock'
        title: Status
        type: entities
    icon: 'mdi:car'
